# Site settings
title: Shelby Cox
email: spcox@umich.edu
description: > # this means to ignore newlines until "baseurl:"
   I am a graduate student at the University of Michigan working with David Speyer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.shelbycox.github.io" # the base hostname & protocol for your site
production_url: "https://www.shelbycox.github.io"
github_username: shelbycox
permalink: /blog/:year/:month/:title.html

sass:
  style: compressed

collections:
  publications:
    output: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
